### ISSUE TITLE
rh423-sync only pull public and does also update ~/rh423_solutions?

### ISSUE THREAD

**Issue by laubersm** [tmichett/rh423_labs#3]
(it might be late, I might be missing something)
It appears that the rh423-sync start command will do a git pull in /home/student/Github/rh423_labs_public/
but then it never syncs up the /home/student/rh423_solutions directory from that.

The rh423-setup script has the git clone AND running ansible-playbook solution_files.yml

I'm not changing anything while I am this blurry eyed but we need to look into this since I think that script has to go on classroom?

(and there is both a git pull for rh423_labs and the Grading_Script_Copy.yml playbook)

**Comment by tmichett** [comment]
@laubersm -

You are correct and I think I know what has happened. We need to have the collection installed. With RHEL 8.5, I am guessing the "Synchronize" might not be around so the playbook fails. I'm thinking I might go ahead and get the collection stuff installed and be checked into the repository, so when it does the Git Pull it will be on the system. I think that is probably the safest way. That is/was one of the things I wanted to check and validate. I know that the playbook was and did work running locally from my system, but I think that is probably an artifact that still needs tested some. 

I also need to fix the Sync script.

Travis

**Comment by laubersm** [comment]
The playbook runs for me manually, it just needs to be added to the sync script.

**Comment by tmichett** [comment]
@laubersm -

I misread some things I thought you said the "setup" and not the "sync". I definitely need to fix the "sync" command.

**Comment by laubersm** [comment]
My concern is fixed - covered in issue #4
