### ISSUE TITLE
Update script to Synchronize Solutions

### ISSUE THREAD

**Issue by tmichett** [tmichett/rh423_labs#4]
Need to modify the following script:

https://github.com/tmichett/rh423_labs/blob/main/Playbooks/Infrastructure/Files/Scripts/grading/lab-rh423-sync

Command should run this playbook:

https://github.com/tmichett/rh423_labs_public/blob/main/Playbooks/solution_files.yml

**Comment by laubersm** [comment]
I updated the script (got tired of doing it by hand) - just a copy of the lines from the setup script to the sync script. It is doing what I need.

**Comment by tmichett** [comment]
Took updated solution script per @laubersm and copied to the "Classroom" grading scripts directory too!

Needed two copies, one for the Classroom and one for workstation.
